apiVersion: apps/v1
kind: Deployment
metadata:
  name: florist-landing-page
  namespace: testing
  labels:
    app: florist-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: florist-landing
  template:
    metadata:
      labels:
        app: florist-landing
    spec:
      containers:
      - name: florist-landing
        image: docker.io/diwamln/florist-landing:build-14-da3ae82
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: florist-landing-service
  namespace: testing
spec:
  selector:
    app: florist-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30777 # Port akses manual via IP VPS
  type: NodePort
