apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage-vito-app
  namespace: prod
  labels:
    app: landingpage-vito
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landingpage-vito
  template:
    metadata:
      labels:
        app: landingpage-vito
    spec:
      containers:
      - name: landingpage-vito
        image: docker.io/diwamln/landingpage-vito:build-13-3f87d3d
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: landingpage-vito-service
  namespace: prod
spec:
  selector:
    app: landingpage-vito
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033 # Port akses manual via IP VPS
  type: NodePort
