apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-booking-app
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-booking
  template:
    metadata:
      labels:
        app: room-booking
    spec:
      initContainers:
      - name: migration
        image: docker.io/diwamln/room-booking:latest
        # PAKSA CLEAR CACHE AGAR TIDAK PAKAI SQLITE
        command: ["sh", "-c", "php artisan config:clear && php artisan migrate --force"]
        envFrom:
        - secretRef:
            name: laravel-secrets
      
      containers:
      - name: room-booking
        image: docker.io/diwamln/room-booking:latest
        # PAKSA CLEAR CACHE SEBELUM SERVE
        command: ["sh", "-c", "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=8000"]
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: laravel-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: room-booking-service
  namespace: testing
spec:
  selector:
    app: room-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32222
  type: NodePort