apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-booking-app
  namespace: testing
spec:
  replicas: 1 # Untuk testing 1 cukup
  selector:
    matchLabels:
      app: room-booking
  template:
    metadata:
      labels:
        app: room-booking
    spec:
      initContainers:
      - name: migration
        image: docker.io/diwamln/room-booking:latest
        command: ["php", "artisan", "migrate", "--force"]
        envFrom:
        - secretRef:
            name: laravel-secrets
      
      containers:
      - name: room-booking
        image: docker.io/diwamln/room-booking:latest
        # KUNCI: Kita jalankan artisan serve agar container bisa diakses HTTP langsung
        command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
        ports:
        - containerPort: 8000 # Port default artisan serve
        envFrom:
        - secretRef:
            name: laravel-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: room-booking-service
  namespace: testing
spec:
  selector:
    app: room-booking
  ports:
    - protocol: TCP
      port: 80          # Port internal cluster
      targetPort: 8000  # Harus diarahkan ke 8000 (artisan serve)
      nodePort: 32222   # Akses dari luar via IP_NODE:32222
  type: NodePort