apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-isp-app
  namespace: testing
  labels:
    app: landing-page-isp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page-isp
  template:
    metadata:
      labels:
        app: landing-page-isp
    spec:
      containers:
        - name: landing-page-isp
          image: docker.io/diwamln/landing-page-isp:build-5-37720a5
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-isp-service
  namespace: testing
spec:
  selector:
    app: landing-page-isp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30077 # Port akses manual via IP VPS
  type: NodePort
